repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: file-contents-sorter
      - id: check-case-conflict
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: end-of-file-fixer
        exclude: '\.bib$'
      - id: trailing-whitespace
        files: ".*\\.(?:tex|py)$"
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.0
    hooks:
      - id: american-eg-ie
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
            [
              "--emph=et al.",
              "--emph=a priori",
              "--emph=a posteriori",
              '--regex=naive=\bna(i|\\"i)ve',
            ]
#      - id: csquotes
#      - id: ensure-labels-for-sections
      - id: no-space-in-cite
      - id: tilde-cite
      - id: unique-labels

  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.23.3
    hooks:
      - id: latexindent
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
      - id: poetry-install

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell mainmatter/
        language: python
        types: [ text ]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.3'  # pick a git hash / tag to point to
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.3.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
        args: ["--line-length=100"]

#  - repo: https://github.com/nbQA-dev/nbQA
#    rev: 1.7.1
#    hooks:
#      - id: nbqa-black
#      - id: nbqa-pyupgrade
#        args: ["--py37-plus"]
#      - id: nbqa-isort
#        args: ["--float-to-top"]
